-- Menu Generation Database Schema
-- Create the database
CREATE DATABASE IF NOT EXISTS menu_gen;
USE menu_gen;

-- Create meals table
CREATE TABLE IF NOT EXISTS meals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    protein VARCHAR(100),
    cuisine VARCHAR(100),
    cook_time VARCHAR(100),
    cook_method VARCHAR(100),
    source VARCHAR(255),
    category VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert the provided meal data
INSERT INTO meals (name, protein, cuisine, cook_time, cook_method, source, category) VALUES
('Magloobeh', 'Chicken', 'Latin', '> 30 minutes', 'Stovetop', 'Head', 'Main'),
('Burritos', 'Beef', 'Latin', '> 30 minutes', 'Stovetop', 'Head', 'Main'),
('Burritos Barbacoa', 'Beef', 'Latin', '2 hours', 'Pressure Cooker', 'Baba', 'Main'),
('Beef Stroganoff', 'Beef', 'European', '2 hours', 'Stovetop', 'BH&G Cookbook', 'Main'),
('Jambalaya', 'Chicken', 'American', '2 hours', 'Stovetop', 'One Pot Cooking Cookbook', 'Main'),
('Mujaddarah', 'Vegetarian', 'Arabic', '1 hour', 'Stovetop', 'Arabic Cookbook (Tata F)', 'Main'),
('Hummus and Fixings', 'Vegetarian', 'Arabic', '1 hour', 'Pressure Cooker', 'Baba Recipe', 'Main'),
('Bamya', 'Beef', 'Arabic', '>30 minutes', 'Stovetop', 'Mama', 'Main'),
('Basaleh', 'Beef', 'Arabic', '>30 minutes', 'Stovetop', 'Mama', 'Main'),
('Kefta bi Siniya', 'Beef', 'Arabic', '2 hours', 'Oven', 'Mama', 'Main'),
('Texas BBQ Chili', 'Beef', 'American', '< 2 hours', 'Slow Cooker', 'Pinterest', 'Main'),
('Shorabet Addas', 'Vegetarian', 'Arabic', '2 hours', 'Stovetop', 'Arabic Cookbook (Tata F)', 'Soup'),
('Pizza', 'Vegetarian', 'American', '< 2 hours', 'Pizza Oven', '', 'Main'),
('Pizza', 'Beef', 'American', '< 2 hours', 'Pizza Oven', '', 'Main'),
('Black Pepper Chicken', 'Chicken', 'Asian', '1 hour', 'Stovetop', 'Pinterest', 'Main'),
('Garlic Eggplant', 'Vegetarian', 'Asian', '1 hour', 'Stovetop', 'Pinterest', 'Main'),
('Pulled Pork', 'Pork', 'American', '< 2 hours', 'Smoker', 'Baba', 'Main'),
('Spaghetti and Meatballs', 'Beef', 'American', '1 hour', 'Stovetop', 'Head', 'Main'),
('Moroccan Chicken', 'Chicken', 'Arabic', '2 hours', 'Stovetop', 'One Pot Cooking Cookbook', 'Main'),
('Fatoosh', 'Vegetarian', 'Arabic', '> 30 minutes', 'Oven', 'Arabic Cookbook', 'Salad'),
('Cashew Chicken', 'Chicken', 'Asian', '1 hour', 'Stovetop', 'Pinterest', 'Main'),
('Roasted Sausage and Vegetables', 'Pork, Beef', 'American', '1 hour', 'Oven', 'Head', 'Main'),
('Beef Barley Soup', 'Beef', 'Arabic', '2 hours', 'Stovetop', 'Arabic Cookbook', 'Soup'),
('Spinach Cheese Lasagna', 'Vegetarian', 'Italian', '< 2 hours', 'Oven', 'BH&G Cookbook', 'Main'),
('Lasagna', 'Beef', 'Italian', '< 2 hours', 'Oven', 'BH&G Cookbook', 'Main'),
('Roasted Ginger Salmon', 'Fish', 'American', '< 2 hours', 'Oven', '', 'Main'),
('Pomegranate Olive Mint Salsa', 'Vegetarian', 'American', '1 hour', '', '', 'Salad'),
('Steak', 'Beef', 'American', '1 hour', 'Grill', 'Head', 'Main'),
('Magloobet', 'Beef', 'Arabic', '< 2 hours', 'Stovetop', 'Arabic Cookbook (Tata F)', 'Main'),
('Coosa Mahshie', 'Beef', 'Arabic', '< 2 hours', 'Stovetop', 'Arabic Cookbook', 'Main'),
('Waraa Inab', 'Vegetarian', 'Arabic', '< 2 hours', 'Stovetop', 'Arabic Cookbook (Tata F)', 'Main'),
('Lasagna Soup', 'Beef', 'American', '< 2 hours', 'Slow Cooker', 'Pinterest', 'Soup'),
('Chaana Dal with Cauliflour, cashews, & Coconut', 'Vegetarian', 'Indian', '2 hours', 'Stovetop', 'Pinterest', 'Main'),
('Chili Lime One Sheet Salmon', 'Fish', 'American', '2 hours', 'Oven', 'Pinterest', 'Main'),
('Fettat Hummus', 'Vegetarian', 'Arabic', '2 hours', 'Oven', 'Arabic Cookbook', 'Main'),
('Fettan Djaj', 'Chicken', 'Arabic', '2 hours', 'Oven', 'Arabic Cookbook', 'Main'),
('Chicken Quesadillas', 'Chicken', 'Latin', '2 hours', 'Stovetop', 'Head', 'Main'),
('Philly Cheesesteaks', 'Beef', 'American', '2 hours', 'Stovetop', 'Head', 'Main'),
('Kushary', 'Vegetarian', 'Arabic', '1 hour', 'Stovetop', 'Arabic Cookbook', 'Main'),
('Creamy Baked Potato Bacon Soup', 'Pork', 'American', '2 hours', 'Stovetop', 'allrecipes.com', 'Soup'),
('Butter Chicken', 'Chicken', 'Indian', '< 2 hours', 'Slow Cooker', 'Pinterest', 'Main'),
('Khubsey, Jhibney, wa Bateekha', 'Vegetarian', 'Arabic', '< 2 hours', '', 'Head', 'Main'),
('Breakfast for Dinner', 'Vegetarian', 'American', '2 hours', 'Griddle', 'Head', 'Main'),
('Italian Beef Stew', 'Beef', 'American', '2 hours', 'Crockpot', 'Pinterest', 'Main'),
('Thai Chicken Soup', 'Chicken', 'Asian', '2 hours', 'Crockpot', 'Pinterest', 'Soup'),
('Grilled Chicken', 'Chicken', 'American', '2 hours', 'Grill', 'Head', 'Main'),
('Kibbeh', 'Beef', 'Arabic', '2 hours', 'Oven', 'Suhtein', 'Main'),
('Tandoor Chicken', 'Chicken', 'Indian', '2 hours', 'Grill', '', 'Main'),
('Singapore Chow Mein', 'Chicken', 'Asian', '2 hours', 'Wok', '', 'Main'),
('Chow Mein', 'Chicken', 'Asian', '< 2 hours', 'Wok', '', 'Main'),
('Cream of Chicken Bake', 'Chicken', 'American', '2 hours', 'Oven', 'Campbell''s', 'Main'),
('Meatloaf', 'Beef', 'American', '2 hours', 'Oven', 'Pioneer Woman', 'Main'),
('Hamburgers', 'Beef', 'American', '2 hours', 'Grill', '', 'Main'),
('Chicken Biryani', 'Chicken', 'Indian', '2 hours', 'Stovetop', 'Baba', 'Main'),
('Chicken Noodle Soup', 'Chicken', 'American', '< 2 hours', 'Stovetop', 'Mama', 'Soup'),
('Grilled Cheese Sandwiches/Tomato Soup', 'Vegetarian', 'American', '< 2 hours', 'Griddle', '', 'Main'),
('Tacos-Fish', 'Fish', 'Latin', '< 2 hours', 'Oven', '', 'Main'),
('Tacos', 'Beef', 'Latin', '1 hour', 'Stovetop', '', 'Main'),
('Enchiladas', 'Chicken', 'Latin', '2 hours', 'Oven', '', 'Main'),
('Waffles and Fried Chicken', 'Chicken', 'American', '2 hours', 'Oven', '', 'Main'),
('Malfouf', 'Beef', 'Arabic', '2 hours', 'Stovetop', '', 'Main'),
('Fried Fish with Baqdoonsieh', 'Fish', 'Arabic', '< 1 hour', '', 'Fish Market', 'Main'),
('Taco Salad', 'Beef', 'American', '1 hour', 'Stovetop', '', 'Main'),
('Sweet Teriyaki Beef Skewers (overnight)', 'Beef', 'Asian', '2 hours', 'Grill', 'Pinterest', 'Main'),
('Roasted Tri-tip', 'Beef', 'American', '2 hours', 'Oven', 'Baba', 'Main'),
('Zuppa Toscana', 'Beef', 'Italian', '2 hours', 'Crockpot', 'Pinterest', 'Soup'),
('Chili Dogs', 'Pork', 'American', '2 hours', 'Stovetop', '', 'Main'),
('Sausage and Veggie Bake', 'Pork', 'American', '30 minutes', 'Oven', 'Pinterest', 'Main'),
('Gumbo', 'Chicken', 'American', '2 hours', 'Stovetop', 'Better Homes and Garden', 'Soup'),
('Citrus Grilled Chicken', 'Chicken', 'American', '2 hours', 'Grill', '', 'Main'),
('Cottage Pie', 'Beef', 'American', '2 hours', 'Oven', 'Pinterest', 'Main'),
('One Pot Chili Mac', 'Beef', 'American', '1 hour', 'Stovetop', 'Pinterest', 'Main'),
('Shish Kebab', 'Beef', 'Arabic', '2 hours', 'Grill', '', 'Main'),
('Chicken Kebab', 'Chicken', 'Arabic', '2 hours', 'Grill', '', 'Main'),
('Vegetarian Korma', 'Vegetarian', 'Indian', '2 hours', 'Stovetop', 'Pinterest', 'Main'),
('Quiche', 'Vegetarian', 'American', '2 hours', 'Oven', '', 'Main'),
('Ribs', 'Beef', 'American', '2 hours', 'Smoker', 'Baba', 'Main'),
('Pannini Sandwiches', 'Beef', 'Italian', '1 hour', 'Griddle', '', 'Main'),
('Shawerma Sandwiches', 'Lamb', 'Arabic', '2 hours', 'Griddle', 'Baba', 'Main'),
('Shrimp Fried Rice', 'Fish', 'Asian', '2 hours', 'Wok', '', 'Main'),
('Chicken Fried Rice', 'Chicken', 'Asian', '1 hour', 'Wok', '', 'Main'),
('Kefta Kebabs', 'Beef', 'Arabic', '2 hours', 'Grill', '', 'Main'),
('Pesto Chicken Pasta', 'Chicken', 'Italian', '30 minutes', 'Stovetop', '', 'Main'),
('Asian Rice Bowl', 'Chicken', 'Asian', '1 hour', 'Stovetop', '', 'Main'),
('Thai Red Curry', 'Vegetarian', 'Asian', '2 hours', 'Crockpot', 'Pinterest', 'Main'),
('Spicy Sweet Potatoes with Pasta', 'Vegetarian', 'Asian', '2 hours', 'Oven', 'Sunset magazine', 'Main'),
('Grilled Fish', 'Fish', 'Arabic', '30 minutes', 'Grill', '', 'Main'),
('Minestrone Soup', 'Pork', 'Italian', '30 minutes', 'Crockpot', 'Pinterest', 'Soup'),
('Beef Burrito Bowl', 'Beef', 'Latin', '30 minutes', 'Stovetop', 'Pinterest', 'Main'),
('Thai Green Curry Chicken', 'Chicken', 'Asian', '30 minutes', 'Stovetop', 'Pinterest', 'Main'),
('Shrimp Fettucine', 'Fish', 'Italian', '1 hour', 'Stovetop', '', 'Main'),
('Falafel sandwiches', 'Vegetarian', 'Arabic', '2 hours', 'Stovetop', 'Nora''s Cookbook', 'Main'),
('Sliders', 'Beef', 'American', '2 hours', 'Oven', '', 'Main'),
('Shrimp and Veggie Boil', 'Fish', 'American', '2 hours', 'Stovetop', '', 'Main'),
('Eggplant Parm Ciabattas', 'Vegetarian', 'Italian', '1 hour', 'Griddle', '', 'Main'),
('Latin Cornbread Casserole', 'Beef', 'Latin', '2 hours', 'Oven', 'Pinterest', 'Main'),
('Korean Barbecue Beef', 'Beef', 'Asian', '2 hours', 'Stovetop', 'Pinterest', 'Main'),
('Quinoa Sweet Potato Chili', 'Vegetarian', 'American', '2 hours', 'Crockpot', 'Pinterest', 'Main'),
('Frittata', 'Vegetarian', 'American', '2 hours', 'Oven', '', 'Main'),
('Coconut Curry Shrimp', 'Fish', 'Asian', '1 hour', 'Wok', 'Pinterest', 'Main'),
('Garlic Eggplant with Tofu', 'Vegetarian', 'Asian', '2 hours', 'Wok', 'allrecipes', 'Main'),
('Moroccan Sweet Potato Lentil Stew', 'Vegetarian', 'Arabic', '1 hour', 'Stovetop', 'Pinterest', 'Main'),
('Cobb Salad', 'Beef', 'American', '1 hour', '', '', 'Main'),
('Jaimaican Jerk Chicken', 'Chicken', 'American', '1 hour', 'Grill', '', 'Main'),
('Chicken Adobo', 'Chicken', 'Asian', '2 hours', 'Slow Cooker', 'Pinterest', 'Main'),
('Spanakopita', 'Vegetarian', 'Arabic', '2 hours', 'Oven', 'Orthodox Cookbook', 'Main'),
('Everything Bagel Chicken', 'Chicken', 'American', '1 hour', 'Oven', 'Pinterest', 'Main'),
('Indian Chicken Korma', 'Chicken', 'Indian', '2 hours', 'Stovetop', 'Pinterest', 'Main'),
('Honey Garlic Glazed Salmon', 'Fish', 'American', '< 30 minutes', 'Oven', 'Pinterest', 'Main'),
('Greek Lemon Chicken Sheet Pan', 'Chicken', 'American', '< 30 minutes', 'Oven', 'Pinterest', 'Main'),
('Spincah, Black Bean, Chicken Enchiladas', 'Chicken', 'Latin', '1 hour', 'Oven', '', 'Main'),
('Gnocchi and Vegetable Sheet Pan', 'Vegetarian', 'American', '1 hour', 'Oven', 'Pinterest', 'Main'),
('Beef and Broccoli Stir Fry', 'Beef', 'Asian', '1 hour', 'Wok', 'Dinner Then Dessert', 'Main'),
('In N Out Cheeseburger Salad', 'Beef', 'American', '2 hours', 'Grill', 'Pinterest', 'Main'),
('Ratatouille', 'Vegetarian', 'European', '2 hours', 'Oven', 'Pinterest', 'Main'),
('Corned Beef with warm cabbage salad', 'Beef', 'European', '2 hours', 'Oven', 'Pinterest', 'Main'),
('Seafood Chowder', 'Fish', 'American', '1 hour', 'Crockpot', 'Pinterest', 'Soup'),
('Beef Barley Soup', 'Beef', 'Arabic', '1 hour', 'Stovetop', 'Sahtein', 'Soup'),
('Tah-chin (Persian Crunchy RIce and Chicken)', 'Chicken', 'Arabic', '2 hours', 'Stovetop', 'Pinterest', 'Main'),
('Calzone', 'Beef', 'American', '2 hours', 'Oven', '', 'Main'),
('40 Clove Garlic Chicken and Potatoes', 'Chicken', 'American', '2 hours', 'Oven', 'Pinterest', 'Main'),
('Moussaka', 'Beef', 'Arabic', '2 hours', 'Oven', '', 'Main'),
('Panang Tofu Curry', 'Vegetarian', 'Asian', '1 hour', 'Stovetop', 'Pinterest', 'Main'),
('Morroccan Chicken and Rice with dates', 'Chicken', 'Arabic', '2 hours', 'Stovetop', 'Pinterest', 'Main'),
('Thai Chicken Soup', 'Chicken', 'Asian', '2 hours', 'Slow Cooker', 'Pinterest', 'Soup'),
('Meatball Sandwiches', 'Beef', 'American', '< 30 minutes', 'Oven', '', 'Main'),
('Sloppy Joes', 'Beef', 'American', '1 hour', 'Stovetop', '', 'Main'),
('Morroccan Chicken veggies and Coucous', 'Chicken', 'Arabic', '2 hours', 'Stovetop', 'Cookbook', 'Main'),
('Bangers and Mash', 'Pork', 'European', '1 hour', 'Stovetop', '', 'Main'),
('Eggs and Potatoes', 'Vegetarian', 'Arabic', '< 30 minutes', 'Stovetop', '', 'Main'),
('Tomato Tart', 'Vegetarian', 'American', '1 hour', 'Oven', '', 'Main'),
('Lentil Soup', 'Vegetarian', 'Arabic', '< 30 minutes', 'Stovetop', 'Aunty Fathia''s Recipe', 'Main'),
('Sausage Roasted B Sprouts...', 'Pork', 'American', '1 hour', 'Oven', 'Pinterest', 'Main'),
('Ravioli Lasagna', 'Beef', 'American', '2 hours', 'Slow Cooker', 'Pinterest', 'Main'),
('Smoked Short RIbs', 'Beef', 'American', '2 hours', 'Grill', '', 'Main'),
('Italian Sub Salad', 'Beef', 'Italian', '< 30 minutes', '', '', 'Main'),
('Keto Green Chili Chicken', 'Chicken', 'American', '1 hour', 'Oven', 'Pinterest', 'Main'),
('Stuffed Manicotti Shells', 'Beef', 'Italian', '2 hours', 'Oven', 'Pinterest', 'Main'),
('Sausage Kale Soup', 'Pork', 'American', '< 30 minutes', 'Stovetop', 'Pinterest', 'Soup'),
('Spicy Thai Chicken Ramen', 'Chicken', 'Asian', '1 hour', 'Stovetop', 'Pinterest', 'Soup'),
('Korean-style Spicy Coleslaw', 'Vegetarian', 'Asian', '< 30 minutes', '', 'Pinterest', 'Salad');

-- Create indexes for better performance
CREATE INDEX idx_protein ON meals(protein);
CREATE INDEX idx_cuisine ON meals(cuisine);
CREATE INDEX idx_cook_time ON meals(cook_time);
CREATE INDEX idx_cook_method ON meals(cook_method);
CREATE INDEX idx_category ON meals(category); 